### ISSUE TITLE
Dead?

### ISSUE THREAD

**Issue by goodmind** [ruse-lang/ruse#1]
Is this project dead?

**Comment by AndrewBrinker** [comment]
Hey, no, it is not dead. I've just been busy. I took a position teaching a university course in addition to my day job and didn't really have time to work on this while I was doing that.

I would like to get back into working on this soon. I will say though (and I believe this is said in the README and on the website as well) that this project is at the moment largely for my own edification and I don't make any promises about rate of development or readiness for serious use.
