### ISSUE TITLE
process didn't exit successfully

### ISSUE THREAD

**Issue by 3442853561** [ruse-lang/ruse#2]
Finished dev [unoptimized + debuginfo] target(s) in 0.1 secs
     Running `target\debug\ruse.exe`
thread 'main' panicked at 'not yet implemented', src/ruse\read\parse\mod.rs:18
note: Run with `RUST_BACKTRACE=1` for a backtrace.
error: process didn't exit successfully: `target\debug\ruse.exe` (exit code: 101)

**Comment by AndrewBrinker** [comment]
Yes, that's because large portions of the project remain unimplemented. I'm working on it, but I'm not making promises about when it will be ready.
